<template>
        <div class="container">
            <div class="row justify-content-center" v-show="$gate.isAdminOrAccounts()">          
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <p>REPORTS</p>
                    </div>
                    <div class="card-body">
                        <form @submit.prevent="generateReport" @keydown="form.onKeydown($event)">                        
                        <div class="row">
                            <fieldset class="col-md-3">
                                <legend><h5>Client Detailed Reports</h5></legend>
                                    <div class="row">                                    
                                        <div class="col-md-12">
                                            <!-- <h6> <router-link to="/reports/drivers/commissions">Commissions:</router-link> Generate all driver statements on completed trips.</h6>
                                            <hr>
                                            <h6><router-link to="/reports/drivers/trips">Trips: </router-link> Driver &amp; trip reports and statements</h6>
                                            <hr> -->
                                            <h6><router-link to="/reports/clients">Client Trip Reports: </router-link> Client custom trip reports &amp; generate invoice on closed trips</h6>
                                            <!-- <h6><router-link to="/">Expenses: </router-link></h6>
                                            <h6><router-link to="/">Schedules: </router-link></h6> -->
                                        </div>
                                    </div>
                                    <!-- end row -->
                            </fieldset>
                            <fieldset class="col-md-3">
                                <legend><h5>Summary Reports</h5></legend>
                                    <div class="row">                                    
                                        <div class="col-md-12">
                                            <h6> <router-link to="/reports/commissions">Sales, Expenses &amp; Commissions:</router-link> Generate all driver commission statements on completed worksheets.</h6>
                                            <hr>
                                            <!-- <h6><router-link to="/">Trips: </router-link> Driver trip reports, and statements</h6>
                                            <h6><router-link to="/">Vehicles: </router-link></h6>
                                            <h6><router-link to="/">Expenses: </router-link></h6>
                                            <h6><router-link to="/">Schedules: </router-link></h6> -->
                                        </div>
                                    </div>
                                    <!-- end row -->
                            </fieldset>
                            <fieldset class="col-md-3">
                                <legend><h5>Work Sheet Reports</h5></legend>
                                    <div class="row">                                    
                                        <div class="col-md-12">
                                            <h6> <router-link to="/reports/worksheets">General Work Sheet:</router-link> Itemized details of a single driver worksheet report.</h6>
                                            <hr>
                                            <!-- <h6><router-link to="/">Trips: </router-link> Driver trip reports, and statements</h6>
                                            <h6><router-link to="/">Vehicles: </router-link></h6>
                                            <h6><router-link to="/">Expenses: </router-link></h6>
                                            <h6><router-link to="/">Schedules: </router-link></h6> -->
                                        </div>
                                    </div>
                                    <!-- end row -->
                            </fieldset>
                            <fieldset class="col-md-3">
                                <legend><h5>Invoicing Reports</h5></legend>
                                    <div class="row">                                    
                                        <div class="col-md-12">
                                            <h6> <router-link to="/reports/invoices">Client Invoice Reports:</router-link> View all client invoice reports generated by date.</h6>
                                            <hr>
                                            <!-- <h6><router-link to="/">Trips: </router-link> Driver trip reports, and statements</h6>
                                            <h6><router-link to="/">Vehicles: </router-link></h6>
                                            <h6><router-link to="/">Expenses: </router-link></h6>
                                            <h6><router-link to="/">Schedules: </router-link></h6> -->
                                        </div>
                                    </div>
                                    <!-- end row -->
                            </fieldset>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div v-show="!$gate.isAdminOrAccounts()">
            <not-found></not-found>
        </div>
    </div>
</template>
<script>
export default {
    
    data(){

        return{
            form: new Form({
                date1: '',
                date2: ''

            })
        }
    }
}
</script>
<style scoped>
fieldset { border:1px solid #c2c2c2; margin: 5px; border-radius: 3px; }
    .form-control{ border-radius: 0px; }

    legend {
        padding: 0.2em 0.5em;
        /* border:1px solid #c2c2c2; */
        color:#070707;
        font-size:90%;
        text-align:left;
        width: auto;
    }

    .form-control-sm {
        height: calc(1.0em + 0.5rem + 2px);
        padding: 0.75rem 0.5rem;
    }
    label:not(.form-check-label):not(.custom-file-label) {
        font-weight: 500;
    }
    label {
        margin-bottom: 0.2rem;
        color: #245d73;
    }
    .form-group {
        margin-bottom: 0.5rem;
    }
    h5, .h5 {
        font-size: 15px;
        font-weight: 600;
        margin-bottom: 0rem;
        
    }
</style>

